=== a7rk/MeteoalarmCard/src/localize/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "required": [
        "$schema",
        "common",
        "error",
        "editor",
        "events",
        "messages"
    ],
    "properties": {
         "$schema": {
              "$id": "#/properties/%24schema",
              "type": "string"
         },
        "common": {
            "$id": "#/properties/common",
            "type": "object",
            "required": [
                "name",
                "description",
                "expected",
                "unavailable"
            ],
            "properties": {
                "name": {
                    "$id": "#/properties/common/properties/name",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/common/properties/description",
                    "type": ["string", "null"]
                },
                "expected": {
                    "$id": "#/properties/common/properties/expected",
                    "type": ["string", "null"]
                },
                "unavailable": {
                    "$id": "#/properties/common/properties/unavailable",
                    "type": "object",
                    "required": [
                        "long",
                        "short"
                    ],
                    "properties": {
                        "long": {
                            "$id": "#/properties/common/properties/unavailable/properties/long",
                            "type": ["string", "null"]
                        },
                        "short": {
                            "$id": "#/properties/common/properties/unavailable/properties/short",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "error": {
            "$id": "#/properties/error",
            "type": "object",
            "required": [
                "missing_entity",
                "invalid_integration",
                "invalid_scaling_mode",
                "invalid_display_mode",
                "entity_invalid"
            ],
            "properties": {
                "missing_entity": {
                    "$id": "#/properties/error/properties/missing_entity",
                    "type": ["string", "null"]
                },
                "invalid_integration": {
                    "$id": "#/properties/error/properties/invalid_integration",
                    "type": ["string", "null"]
                },
                "invalid_scaling_mode": {
                    "$id": "#/properties/error/properties/invalid_scaling_mode",
                    "type": ["string", "null"]
                },
                "invalid_display_mode": {
                    "$id": "#/properties/error/properties/invalid_display_mode",
                    "type": ["string", "null"]
                },
                "entity_invalid": {
                    "$id": "#/properties/error/properties/entity_invalid",
                    "type": "object",
                    "required": [
                        "single",
                        "multiple"
                    ],
                    "properties": { 
                        "single": {
                            "$id": "#/properties/error/properties/entity_invalid/properties/single",
                            "type": ["string", "null"]
                        },
                        "multiple": {
                            "$id": "#/properties/error/properties/entity_invalid/properties/multiple",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "editor": {
            "$id": "#/properties/editor",
            "type": "object",
            "required": [
                "entity",
                "entities",
                "integration",
                "required",
                "recommended",
                "override_headline",
                "hide_when_no_warning",
                "hide_caption",
                "disable_swiper",
                "description",
                "error",
                "scaling_mode",
                "scaling_mode_options",
                "display_mode",
                "display_mode_options"
            ],
            "properties": {
                "entity": {
                    "$id": "#/properties/editor/properties/entity",
                    "type": ["string", "null"]
                },
                "entities": {
                    "$id": "#/properties/editor/properties/entities",
                    "type": ["string", "null"]
                },
                "integration": {
                    "$id": "#/properties/editor/properties/integration",
                    "type": ["string", "null"]
                },
                "required": {
                    "$id": "#/properties/editor/properties/required",
                    "type": ["string", "null"]
                },
                "recommended": {
                    "$id": "#/properties/editor/properties/recommended",
                    "type": ["string", "null"]
                },
                "override_headline": {
                  "$id": "#/properties/editor/properties/override_headline",
                  "type": ["string", "null"]
                },
                "hide_when_no_warning": {
                    "$id": "#/properties/editor/properties/hide_when_no_warning",
                    "type": ["string", "null"]
                },
                "hide_caption": {
                    "$id": "#/properties/editor/properties/hide_caption",
                    "type": ["string", "null"]
                },
                "disable_swiper": {
                    "$id": "#/properties/editor/properties/disable_swiper",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/editor/properties/description",
                    "type": "object",
                    "required": [
                        "start",
                        "current_expected",
                        "slots",
                        "separate_events",
                        "warning_watch_statement_advisory",
                        "end"
                    ],
                    "properties": { 
                        "start": {
                            "$id": "#/properties/editor/properties/description/properties/start",
                            "type": ["string", "null"]
                        },
                        "current_expected": {
                            "$id": "#/properties/editor/properties/description/properties/current_expected",
                            "type": ["string", "null"]
                        },
                        "slots": {
                            "$id": "#/properties/editor/properties/description/properties/slots",
                            "type": ["string", "null"]
                        },
                        "separate_events": {
                            "$id": "#/properties/editor/properties/description/properties/separate_events",
                            "type": ["string", "null"]
                        },
                        "warning_watch_statement_advisory": {
                            "$id": "#/properties/editor/properties/description/properties/warning_watch_statement_advisory",
                            "type": ["string", "null"]
                        },
                        "end": {
                            "$id": "#/properties/editor/properties/description/properties/end",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "error": {
                    "$id": "#/properties/editor/properties/error",
                    "type": "object",
                    "required": [
                        "expected_entity",
                        "too_many_entities",
                        "duplicate"
                    ],
                    "properties": { 
                        "expected_entity": {
                            "$id": "#/properties/editor/properties/error/properties/expected_entity",
                            "type": ["string", "null"]
                        },
                        "too_many_entities": {
                            "$id": "#/properties/editor/properties/error/properties/too_many_entities",
                            "type": ["string", "null"]
                        },
                        "duplicate": {
                            "$id": "#/properties/editor/properties/error/properties/duplicate",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "scaling_mode": {
                    "$id": "#/properties/editor/properties/scaling_mode",
                    "type": ["string", "null"]
                },
                "scaling_mode_options": {
                    "$id": "#/properties/editor/properties/scaling_mode_options",
                    "type": "object",
                    "required": [
                        "disabled",
                        "headline",
                        "scale",
                        "headline_and_scale"
                    ],
                    "properties": {
                        "disabled": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/disabled",
                            "type": ["string", "null"]
                        },
                        "headline": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/headline",
                            "type": ["string", "null"]
                        },
                        "scale": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/scale",
                            "type": ["string", "null"]
                        },
                        "headline_and_scale": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/headline_and_scale",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "display_mode": {
                    "$id": "#/properties/editor/properties/display_mode",
                    "type": ["string", "null"]
                },
                "display_mode_options": {
                    "$id": "#/properties/editor/properties/display_mode_options",
                    "type": "object",
                    "required": [
                        "card",
                        "badge"
                    ],
                    "properties": {
                        "card": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/card",
                            "type": ["string", "null"]
                        },
                        "badge": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/badge",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "events": {
            "$id": "#/properties/events",
            "type": "object",
            "required": [
                "no_warnings",
                "nuclear",
                "hurricane",
                "wind",
                "snow_ice",
                "thunderstorms",
                "fog",
                "high_temperature",
                "low_temperature",
                "coastal_event",
                "sea_event",
                "forest_fire",
                "avalanches",
                "earthquake",
                "volcano",
                "rain",
                "flooding",
                "tornado",
                "air_quality",
                "dust",
                "tsunami"
            ],
            "properties": {
                "no_warnings": {
                    "$id": "#/properties/events/properties/no_warnings",
                    "type": ["string", "null"]
                },
                "nuclear": {
                    "$id": "#/properties/events/properties/nuclear",
                    "type": ["string", "null"]
                },
                "hurricane": {
                    "$id": "#/properties/events/properties/hurricane",
                    "type": ["string", "null"]
                },
                "wind": {
                    "$id": "#/properties/events/properties/wind",
                    "type": ["string", "null"]
                },
                "snow_ice": {
                    "$id": "#/properties/events/properties/snow_ice",
                    "type": ["string", "null"]
                },
                "thunderstorms": {
                    "$id": "#/properties/events/properties/thunderstorms",
                    "type": ["string", "null"]
                },
                "fog": {
                    "$id": "#/properties/events/properties/fog",
                    "type": ["string", "null"]
                },
                "high_temperature": {
                    "$id": "#/properties/events/properties/high_temperature",
                    "type": ["string", "null"]
                },
                "low_temperature": {
                    "$id": "#/properties/events/properties/low_temperature",
                    "type": ["string", "null"]
                },
                "coastal_event": {
                    "$id": "#/properties/events/properties/coastal_event",
                    "type": ["string", "null"]
                },
                "sea_event": {
                    "$id": "#/properties/events/properties/sea_event",
                    "type": ["string", "null"]
                },
                "forest_fire": {
                    "$id": "#/properties/events/properties/forest_fire",
                    "type": ["string", "null"]
                },
                "avalanches": {
                    "$id": "#/properties/events/properties/avalanches",
                    "type": ["string", "null"]
                },
                "earthquake": {
                    "$id": "#/properties/events/properties/earthquake",
                    "type": ["string", "null"]
                },
                "volcano": {
                    "$id": "#/properties/events/properties/volcano",
                    "type": ["string", "null"]
                },
                "rain": {
                    "$id": "#/properties/events/properties/rain",
                    "type": ["string", "null"]
                },
                "flooding": {
                    "$id": "#/properties/events/properties/flooding",
                    "type": ["string", "null"]
                },
                "tornado": {
                    "$id": "#/properties/events/properties/tornado",
                    "type": ["string", "null"]
                },
                "air_quality": {
                    "$id": "#/properties/events/properties/air_quality",
                    "type": ["string", "null"]
                },
                "dust": {
                    "$id": "#/properties/events/properties/dust",
                    "type": ["string", "null"]
                },
                "tsunami": {
                    "$id": "#/properties/events/properties/tsunami",
                    "type": ["string", "null"]
                }
            },
            "additionalProperties": false
        },
        "messages": {
            "$id": "#/properties/messages",
            "type": "object",
            "required": [
                "yellow",
                "orange",
                "red"
            ],
            "properties": {
                "yellow": {
                    "$id": "#/properties/messages/properties/yellow",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/yellow/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/yellow/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/yellow/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                },
                "orange": {
                    "$id": "#/properties/messages/properties/orange",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/orange/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/orange/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/orange/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                },
                "red": {
                    "$id": "#/properties/messages/properties/red",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/red/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/red/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/red/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== a7rk/MeteoalarmCard/src/localize/languages/pt.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Cartão Meteoalarm",
    "description": "O cartão Meteoalarm adverte sobre eventos meteorológicos actuais.",
    "expected": "Esperado",
    "unavailable": {
      "long": "A integração não está disponível",
      "short": "Indisponível"
    }
  },
  "error": {
    "missing_entity": "É necessário especificar a entidade!",
    "invalid_integration": "A integração não é válida!",
    "invalid_scaling_mode": null,
    "invalid_display_mode": null,
    "entity_invalid": {
      "single": "A integração seleccionada não conincide com a entidade seleccionada.",
      "multiple": "A integração seleccionada não conincide com as entidades seleccionadas: {entity}."
    }
  },
  "editor": {
    "entity": "Entidade",
    "entities": null,
    "integration": "Integração",
    "required": "Necessário",
    "recommended": "Recomendado",
    "override_headline": "Modificar cabeçalho",
    "hide_when_no_warning": "Ocultar quando não há avisos",
    "hide_caption": "Ocultar título",
    "disable_swiper": "Desactivar o deslizador de alertas",
    "description": {
      "start": "A integração seleccionada cria múltiplas entidades.",
      "current_expected": "O primeiro com eventos actuais e o segundo com eventos futuros.",
      "slots": "A quantidade exacta criada é determinada pela sua configuracão.",
      "separate_events": "Cada tipo de evento tem uma entidade separada.",
      "warning_watch_statement_advisory": null,
      "end": "Devem ser agregados para não serem perdidos alertas."
    },
    "error": {
      "expected_entity": "Não foi especificada entidade de avisos esperada. Não se irão mostrar eventos futuros.",
      "too_many_entities": "Foram especificadas mais entidades do que esperado. Esperavam-se {expected_entities_count} entidades, mas foram especificadas {selected_entities_count} entidades.",
      "duplicate": "Encontrados duplicados na lista de entidades."
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    },
    "display_mode": null,
    "display_mode_options": {
      "card": null,
      "badge": null
    }
  },
  "events": {
    "no_warnings": "Sem avisos",
    "nuclear": "evento nuclear",
    "tornado": "tornado",
    "hurricane": "furacão",
    "wind": "vento",
    "earthquake": "terremoto",
    "volcano": "vulcão",
    "snow_ice": "neve/gelo",
    "fog": "nevoeiro",
    "high_temperature": "alta temperatura",
    "low_temperature": "baixa temperatura",
    "coastal_event": "fenómeno costeiro",
    "tsunami": "tsunami",
    "sea_event": "evento marinho",
    "forest_fire": "incêndio forestal",
    "avalanches": "avalanches",
    "thunderstorms": "trovoadas",
    "rain": "chuva",
    "flooding": "inundação",
    "air_quality": "qualidade do ar",
    "dust": "pó"
  },
  "messages": {
    "yellow": {
      "event": "Alerta amarelo por {event}",
      "generic": "Alerta amarelo",
      "color": "Amarelo"
    },
    "orange": {
      "event": "Alerta laranja por {event}",
      "generic": "Alerta laranja",
      "color": "Laranja"
    },
    "red": {
      "event": "Alerta vermelho por {event}",
      "generic": "Alerta vermelho",
      "color": "Vermelho"
    }
  }
}

=== a7rk/MeteoalarmCard/src/localize/languages/hu.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Kártya",
    "description": "A Meteoalarm kártya figyelmeztet az aktuális időjárási eseményekre.",
    "expected": "Várható",
    "unavailable": {
      "long": "Az integráció nem elérhető",
      "short": "Nem elérhető"
    }
  },
  "error": {
    "missing_entity": "Az entitások megadása kötelező!",
    "invalid_integration": "Ez az integráció nem érvényes!",
    "invalid_scaling_mode": "Ez a méretezési mód nem érvényes!",
    "invalid_display_mode": null,
    "entity_invalid": {
      "single": "A kiválasztott integráció nem egyezik a kiválasztott entitással.",
      "multiple": "A kiválasztott integráció nem egyezik a kiválasztott entitásokkal: {entity}."
    }
  },
  "editor": {
    "entity": "Entitás",
    "entities": null,
    "integration": "Integráció",
    "required": "Kötelező",
    "recommended": "Ajánlott",
    "override_headline": "Az integráció által biztosított címsor felülírása",
    "hide_when_no_warning": "Elrejtés, ha nincs figyelmeztetés",
    "hide_caption": "Felirat elrejtése",
    "disable_swiper": "Riasztások lapozójának letiltása",
    "description": {
      "start": "A kiválasztott integráció több entitást hoz létre.",
      "current_expected": "Az első az aktuális eseményekkel, a második a jövőbeli eseményekkel.",
      "slots": "A létrehozott pontos mennyiséget a konfigurációja határozza meg.",
      "separate_events": "Minden eseménytípusnak külön entitása van.",
      "warning_watch_statement_advisory": "4 entitás van: figyelmeztetések, figyelések, nyilatkozatok és tanácsadások.",
      "end": "Az összeset hozzá kell adnia, hogy ne maradjon le egyetlen riasztásról sem."
    },
    "error": {
      "expected_entity": "A várható figyelmeztetések entitás nem lett megadva. A jövőbeli események nem jelennek meg.",
      "too_many_entities": "Több entitás lett megadva a vártnál. Várt: {expected_entities_count} entitás, kapott: {selected_entities_count} entitás.",
      "duplicate": "Duplikátumok találhatók az entitások listájában."
    },
    "scaling_mode": "Méretezési mód",
    "scaling_mode_options": {
      "disabled": "Letiltva",
      "headline": "Csak címsor",
      "scale": "Csak méretezés",
      "headline_and_scale": "Címsor és méretezés"
    },
    "display_mode": null,
    "display_mode_options": {
      "card": null,
      "badge": null
    }
  },
  "events": {
    "no_warnings": "Nincs figyelmeztetés",
    "nuclear": "nukleáris esemény",
    "tornado": "tornádó",
    "hurricane": "hurrikán",
    "wind": "szél",
    "earthquake": "földrengés",
    "volcano": "vulkán",
    "snow_ice": "hó/jég",
    "fog": "köd",
    "high_temperature": "magas hőmérséklet",
    "low_temperature": "alacsony hőmérséklet",
    "coastal_event": "tengerparti esemény",
    "tsunami": "cunami",
    "sea_event": "tengeri esemény",
    "forest_fire": "erdőtűz",
    "avalanches": "lavinák",
    "thunderstorms": "zivatarok",
    "rain": "eső",
    "flooding": "árvíz",
    "air_quality": "levegőminőség",
    "dust": "por"
  },
  "messages": {
    "yellow": {
      "event": "Sárga {event} figyelmeztetés",
      "generic": "Sárga figyelmeztetés",
      "color": "Sárga"
    },
    "orange": {
      "event": "Narancs {event} figyelmeztetés",
      "generic": "Narancssárga figyelmeztetés",
      "color": "Narancssárga"
    },
    "red": {
      "event": "Piros {event} figyelmeztetés",
      "generic": "Piros figyelmeztetés",
      "color": "Piros"
    }
  }
}
