=== a7rk/MeteoalarmCard/src/localize/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "required": [
        "$schema",
        "common",
        "error",
        "editor",
        "events",
        "messages"
    ],
    "properties": {
         "$schema": {
              "$id": "#/properties/%24schema",
              "type": "string"
         },
        "common": {
            "$id": "#/properties/common",
            "type": "object",
            "required": [
                "name",
                "description",
                "expected",
                "unavailable"
            ],
            "properties": {
                "name": {
                    "$id": "#/properties/common/properties/name",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/common/properties/description",
                    "type": ["string", "null"]
                },
                "expected": {
                    "$id": "#/properties/common/properties/expected",
                    "type": ["string", "null"]
                },
                "unavailable": {
                    "$id": "#/properties/common/properties/unavailable",
                    "type": "object",
                    "required": [
                        "long",
                        "short"
                    ],
                    "properties": {
                        "long": {
                            "$id": "#/properties/common/properties/unavailable/properties/long",
                            "type": ["string", "null"]
                        },
                        "short": {
                            "$id": "#/properties/common/properties/unavailable/properties/short",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "error": {
            "$id": "#/properties/error",
            "type": "object",
            "required": [
                "missing_entity",
                "invalid_integration",
                "invalid_scaling_mode",
                "invalid_display_mode",
                "entity_invalid"
            ],
            "properties": {
                "missing_entity": {
                    "$id": "#/properties/error/properties/missing_entity",
                    "type": ["string", "null"]
                },
                "invalid_integration": {
                    "$id": "#/properties/error/properties/invalid_integration",
                    "type": ["string", "null"]
                },
                "invalid_scaling_mode": {
                    "$id": "#/properties/error/properties/invalid_scaling_mode",
                    "type": ["string", "null"]
                },
                "invalid_display_mode": {
                    "$id": "#/properties/error/properties/invalid_display_mode",
                    "type": ["string", "null"]
                },
                "entity_invalid": {
                    "$id": "#/properties/error/properties/entity_invalid",
                    "type": "object",
                    "required": [
                        "single",
                        "multiple"
                    ],
                    "properties": { 
                        "single": {
                            "$id": "#/properties/error/properties/entity_invalid/properties/single",
                            "type": ["string", "null"]
                        },
                        "multiple": {
                            "$id": "#/properties/error/properties/entity_invalid/properties/multiple",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "editor": {
            "$id": "#/properties/editor",
            "type": "object",
            "required": [
                "entity",
                "entities",
                "integration",
                "required",
                "recommended",
                "override_headline",
                "hide_when_no_warning",
                "hide_caption",
                "disable_swiper",
                "description",
                "error",
                "scaling_mode",
                "scaling_mode_options",
                "display_mode",
                "display_mode_options"
            ],
            "properties": {
                "entity": {
                    "$id": "#/properties/editor/properties/entity",
                    "type": ["string", "null"]
                },
                "entities": {
                    "$id": "#/properties/editor/properties/entities",
                    "type": ["string", "null"]
                },
                "integration": {
                    "$id": "#/properties/editor/properties/integration",
                    "type": ["string", "null"]
                },
                "required": {
                    "$id": "#/properties/editor/properties/required",
                    "type": ["string", "null"]
                },
                "recommended": {
                    "$id": "#/properties/editor/properties/recommended",
                    "type": ["string", "null"]
                },
                "override_headline": {
                  "$id": "#/properties/editor/properties/override_headline",
                  "type": ["string", "null"]
                },
                "hide_when_no_warning": {
                    "$id": "#/properties/editor/properties/hide_when_no_warning",
                    "type": ["string", "null"]
                },
                "hide_caption": {
                    "$id": "#/properties/editor/properties/hide_caption",
                    "type": ["string", "null"]
                },
                "disable_swiper": {
                    "$id": "#/properties/editor/properties/disable_swiper",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/editor/properties/description",
                    "type": "object",
                    "required": [
                        "start",
                        "current_expected",
                        "slots",
                        "separate_events",
                        "warning_watch_statement_advisory",
                        "end"
                    ],
                    "properties": { 
                        "start": {
                            "$id": "#/properties/editor/properties/description/properties/start",
                            "type": ["string", "null"]
                        },
                        "current_expected": {
                            "$id": "#/properties/editor/properties/description/properties/current_expected",
                            "type": ["string", "null"]
                        },
                        "slots": {
                            "$id": "#/properties/editor/properties/description/properties/slots",
                            "type": ["string", "null"]
                        },
                        "separate_events": {
                            "$id": "#/properties/editor/properties/description/properties/separate_events",
                            "type": ["string", "null"]
                        },
                        "warning_watch_statement_advisory": {
                            "$id": "#/properties/editor/properties/description/properties/warning_watch_statement_advisory",
                            "type": ["string", "null"]
                        },
                        "end": {
                            "$id": "#/properties/editor/properties/description/properties/end",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "error": {
                    "$id": "#/properties/editor/properties/error",
                    "type": "object",
                    "required": [
                        "expected_entity",
                        "too_many_entities",
                        "duplicate"
                    ],
                    "properties": { 
                        "expected_entity": {
                            "$id": "#/properties/editor/properties/error/properties/expected_entity",
                            "type": ["string", "null"]
                        },
                        "too_many_entities": {
                            "$id": "#/properties/editor/properties/error/properties/too_many_entities",
                            "type": ["string", "null"]
                        },
                        "duplicate": {
                            "$id": "#/properties/editor/properties/error/properties/duplicate",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "scaling_mode": {
                    "$id": "#/properties/editor/properties/scaling_mode",
                    "type": ["string", "null"]
                },
                "scaling_mode_options": {
                    "$id": "#/properties/editor/properties/scaling_mode_options",
                    "type": "object",
                    "required": [
                        "disabled",
                        "headline",
                        "scale",
                        "headline_and_scale"
                    ],
                    "properties": {
                        "disabled": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/disabled",
                            "type": ["string", "null"]
                        },
                        "headline": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/headline",
                            "type": ["string", "null"]
                        },
                        "scale": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/scale",
                            "type": ["string", "null"]
                        },
                        "headline_and_scale": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/headline_and_scale",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "display_mode": {
                    "$id": "#/properties/editor/properties/display_mode",
                    "type": ["string", "null"]
                },
                "display_mode_options": {
                    "$id": "#/properties/editor/properties/display_mode_options",
                    "type": "object",
                    "required": [
                        "card",
                        "badge"
                    ],
                    "properties": {
                        "card": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/card",
                            "type": ["string", "null"]
                        },
                        "badge": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/badge",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "events": {
            "$id": "#/properties/events",
            "type": "object",
            "required": [
                "no_warnings",
                "nuclear",
                "hurricane",
                "wind",
                "snow_ice",
                "thunderstorms",
                "fog",
                "high_temperature",
                "low_temperature",
                "coastal_event",
                "sea_event",
                "forest_fire",
                "avalanches",
                "earthquake",
                "volcano",
                "rain",
                "flooding",
                "tornado",
                "air_quality",
                "dust",
                "tsunami"
            ],
            "properties": {
                "no_warnings": {
                    "$id": "#/properties/events/properties/no_warnings",
                    "type": ["string", "null"]
                },
                "nuclear": {
                    "$id": "#/properties/events/properties/nuclear",
                    "type": ["string", "null"]
                },
                "hurricane": {
                    "$id": "#/properties/events/properties/hurricane",
                    "type": ["string", "null"]
                },
                "wind": {
                    "$id": "#/properties/events/properties/wind",
                    "type": ["string", "null"]
                },
                "snow_ice": {
                    "$id": "#/properties/events/properties/snow_ice",
                    "type": ["string", "null"]
                },
                "thunderstorms": {
                    "$id": "#/properties/events/properties/thunderstorms",
                    "type": ["string", "null"]
                },
                "fog": {
                    "$id": "#/properties/events/properties/fog",
                    "type": ["string", "null"]
                },
                "high_temperature": {
                    "$id": "#/properties/events/properties/high_temperature",
                    "type": ["string", "null"]
                },
                "low_temperature": {
                    "$id": "#/properties/events/properties/low_temperature",
                    "type": ["string", "null"]
                },
                "coastal_event": {
                    "$id": "#/properties/events/properties/coastal_event",
                    "type": ["string", "null"]
                },
                "sea_event": {
                    "$id": "#/properties/events/properties/sea_event",
                    "type": ["string", "null"]
                },
                "forest_fire": {
                    "$id": "#/properties/events/properties/forest_fire",
                    "type": ["string", "null"]
                },
                "avalanches": {
                    "$id": "#/properties/events/properties/avalanches",
                    "type": ["string", "null"]
                },
                "earthquake": {
                    "$id": "#/properties/events/properties/earthquake",
                    "type": ["string", "null"]
                },
                "volcano": {
                    "$id": "#/properties/events/properties/volcano",
                    "type": ["string", "null"]
                },
                "rain": {
                    "$id": "#/properties/events/properties/rain",
                    "type": ["string", "null"]
                },
                "flooding": {
                    "$id": "#/properties/events/properties/flooding",
                    "type": ["string", "null"]
                },
                "tornado": {
                    "$id": "#/properties/events/properties/tornado",
                    "type": ["string", "null"]
                },
                "air_quality": {
                    "$id": "#/properties/events/properties/air_quality",
                    "type": ["string", "null"]
                },
                "dust": {
                    "$id": "#/properties/events/properties/dust",
                    "type": ["string", "null"]
                },
                "tsunami": {
                    "$id": "#/properties/events/properties/tsunami",
                    "type": ["string", "null"]
                }
            },
            "additionalProperties": false
        },
        "messages": {
            "$id": "#/properties/messages",
            "type": "object",
            "required": [
                "yellow",
                "orange",
                "red"
            ],
            "properties": {
                "yellow": {
                    "$id": "#/properties/messages/properties/yellow",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/yellow/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/yellow/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/yellow/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                },
                "orange": {
                    "$id": "#/properties/messages/properties/orange",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/orange/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/orange/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/orange/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                },
                "red": {
                    "$id": "#/properties/messages/properties/red",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/red/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/red/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/red/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== a7rk/MeteoalarmCard/src/localize/languages/bg.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Card",
    "description": "Картата Meteoalarm Ви предупреждава за текущите метеорологични събития.",
    "expected": "Очаквано",
    "unavailable": {
      "long": "Интеграцията не е достъпна",
      "short": "Недостъпно"
    }
  },
  "error": {
    "missing_entity": "Изисква се посочване на обекти!",
    "invalid_integration": "Тази интеграция не е валидна!",
    "invalid_scaling_mode": null,
    "invalid_display_mode": null,
    "entity_invalid": {
      "single": "Избраната интеграция не съответства на избрания обект.",
      "multiple": "Избраната интеграция не съответства на избраните обекти: {entity}."
    }
  },
  "editor": {
    "entity": "Обект",
    "entities": null,
    "integration": "Интеграция",
    "required": "Задължително",
    "recommended": "Препоръчително",
    "override_headline": "Заменете заглавието, предоставено от интеграцията",
    "hide_when_no_warning": "Скриване, когато няма предупреждения",
    "hide_caption": "Скриване на надписа",
    "disable_swiper": "Деактивиране на alerts swiper",
    "description": {
      "start": "Избраната интеграция създава множество обекти.",
      "current_expected": "Първият с текущите събития, а вторият с бъдещите.",
      "slots": "The exact amount of them created is determined by it's configuration.",
      "separate_events": "Всеки вид събитие има отделен обект.",
      "warning_watch_statement_advisory": null,
      "end": "Трябва да добавите всички тях, за да сте сигурни, че няма да пропуснете никакви сигнали."
    },
    "error": {
      "expected_entity": "Expected warnings entity haven't been provided. Future event won't be shown.",
      "too_many_entities": "More entities than expected haven't been provided. Expected {expected_entities_count} entities, got {selected_entities_count} entities.",
      "duplicate": "Открити са дубликати в списъка с обекти."
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    },
    "display_mode": null,
    "display_mode_options": {
      "card": null,
      "badge": null
    }
  },
  "events": {
    "no_warnings": "Без опасни явления",
    "nuclear": "ядрено събитие",
    "tornado": "торнадо",
    "hurricane": "ураган",
    "wind": "вятър",
    "earthquake": "земетресение",
    "volcano": "вулкан",
    "snow_ice": "сняг/поледица",
    "fog": "мъгла",
    "high_temperature": "високи температури",
    "low_temperature": "ниски температури",
    "coastal_event": "крайбрежно събитие",
    "tsunami": "цунами",
    "sea_event": "морско събитие",
    "forest_fire": "горски пожари",
    "avalanches": "лавини",
    "thunderstorms": "гръмотевична активност",
    "rain": "дъжд",
    "flooding": "наводнения",
    "air_quality": "качество на въздуха",
    "dust": "прах"
  },
  "messages": {
    "yellow": {
      "event": "Жълт код за {event}",
      "generic": "Жълт код",
      "color": "Жълт"
    },
    "orange": {
      "event": "Оранжев код за {event}",
      "generic": "Оранжев код",
      "color": "Оранжев"
    },
    "red": {
      "event": "Червен код за {event}",
      "generic": "Червен код",
      "color": "Червен"
    }
  }
}

=== a7rk/MeteoalarmCard/src/localize/languages/sk.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Card",
    "description": "Karta Meteoalarm vás upozorní na aktuálne udalosti počasia.",
    "expected": "Očakavanie",
    "unavailable": {
      "long": "Integrácia nie je k dispozícii",
      "short": "Nedostupné"
    }
  },
  "error": {
    "missing_entity": "Je potrebné zadať entitu!",
    "invalid_integration": "Táto integrácia nie je platná!",
    "invalid_scaling_mode": null,
    "invalid_display_mode": null,
    "entity_invalid": {
      "single": "Vybratá integrácia sa nezhoduje s vybratou entitou.",
      "multiple": "Vybratá integrácia sa nezhoduje s vybratými entitami: {entity}."
    }
  },
  "editor": {
    "entity": "Entity",
    "entities": null,
    "integration": "Integrácia",
    "required": "Požadovaný",
    "recommended": "Odporúčané",
    "override_headline": "Prepísať nadpis",
    "hide_when_no_warning": "Skryť, keď nie sú žiadne upozornenia",
    "hide_caption": "Skryť popis",
    "disable_swiper": "Zakázať posúvanie upozornení",
    "description": {
      "start": "Zvolená integrácia vytvára viacero entít.",
      "current_expected": "Prvý s aktuálnymi udalosťami a druhý s budúcimi",
      "slots": "Ich presné množstvo je určené jeho konfiguráciou.",
      "separate_events": "Každý druh udalosti má samostatnú entitu.",
      "warning_watch_statement_advisory": null,
      "end": "Mali by ste ich pridať všetky, aby ste sa uistili, že vám žiadne upozornenia neuniknú."
    },
    "error": {
      "expected_entity": "Nebola poskytnutá entita očakávaných upozornení. Budúca udalosť sa nebude zobrazovať.",
      "too_many_entities": "Nebolo poskytnutých viac entít, ako sa očakávalo. Očakávaných entít: {expected_entities_count}, počet entít: {selected_entities_count}.",
      "duplicate": "V zozname entít sa našli duplikáty."
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    },
    "display_mode": null,
    "display_mode_options": {
      "card": null,
      "badge": null
    }
  },
  "events": {
    "no_warnings": "Žiadne upozornenia",
    "nuclear": "jadrová udalosť",
    "tornado": "tornádo",
    "hurricane": "hurikán",
    "wind": "vietor",
    "earthquake": "zemetrasenie",
    "volcano": "sopka",
    "snow_ice": "sneh/ľad",
    "fog": "hmla",
    "high_temperature": "vysoká teplota",
    "low_temperature": "nízka teplota",
    "coastal_event": "pobrežná udalosť",
    "tsunami": "cunami",
    "sea_event": "námorná udalosť",
    "forest_fire": "lesný požiar",
    "avalanches": "lavíny",
    "thunderstorms": "búrky",
    "rain": "dážď",
    "flooding": "záplavy",
    "air_quality": "kvalitu ovzdušia",
    "dust": "peľ"
  },
  "messages": {
    "yellow": {
      "event": "Žlté {event} varovanie",
      "generic": "Žlté varovanie",
      "color": "Žlté"
    },
    "orange": {
      "event": "Oranžové {event} varovanie",
      "generic": "Oranžové varovanie",
      "color": "Oranžové"
    },
    "red": {
      "event": "Červené {event} varovanie",
      "generic": "Červené varovanie",
      "color": "Červené"
    }
  }
}

=== a7rk/MeteoalarmCard/src/localize/languages/it.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Scheda Meteoalarm",
    "description": "La scheda Meteoalarm ti avvisa degli eventi meteorologici in corso.",
    "expected": "Previsto",
    "unavailable": {
      "long": "L'integrazione non è disponibile",
      "short": "Non disponibile"
    }
  },
  "error": {
    "missing_entity": "È necessario specificare un'entità!",
    "invalid_integration": "Questa integrazione non è valida!",
    "invalid_scaling_mode": null,
    "invalid_display_mode": null,
    "entity_invalid": {
      "single": "L'integrazione selezionata non corrisponde all'entità selezionata.",
      "multiple": "L'integrazione selezionata non corrisponde alle entità selezionate: {entity}."
    }
  },
  "editor": {
    "entity": "Entità",
    "entities": null,
    "integration": "Integrazione",
    "required": "Richiesto",
    "recommended": "Consigliato",
    "override_headline": "Sovrascrivere l'intestazione fornita dall'integrazione",
    "hide_when_no_warning": "Nascondi quando non ci sono avvisi",
    "hide_caption": "Nascondi la descrizione",
    "disable_swiper": "Disabilità lo swipe delle allerte",
    "description": {
      "start": "L'integrazione selezionata crea più entità.",
      "current_expected": "La prima con gli eventi attuali e la seconda con quelli futuri.",
      "slots": "L'esatta quantità è determinata dalla sua configurazione.",
      "separate_events": "Ogni evento ha un'entità propria e separata.",
      "warning_watch_statement_advisory": null,
      "end": "Dovresti aggiungerle tutte per essere sicuro di non perdere nessun avviso."
    },
    "error": {
      "expected_entity": "L'entità di avviso futuro non è stata inserita. Gli eventi futuri non saranno mostrati.",
      "too_many_entities": "Più entità del previsto non sono state fornite. Entita previste: {expected_entities_count}; Entita fornite: {selected_entities_count} entità.",
      "duplicate": "Trovati duplicati nell'elenco delle entità."
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    },
    "display_mode": null,
    "display_mode_options": {
      "card": null,
      "badge": null
    }
  },
  "events": {
    "no_warnings": "Nessun allarme",
    "nuclear": "Nucleare",
    "tornado": "Tornadi",
    "hurricane": "Uragani",
    "wind": "Vento",
    "earthquake": "Terremoti",
    "volcano": "Eruzione vulcanica",
    "snow_ice": "Neve/Ghiaccio",
    "fog": "Nebbia",
    "high_temperature": "Alte temperature",
    "low_temperature": "Basse temperature",
    "coastal_event": "Eventi costieri",
    "tsunami": "Tsunami",
    "sea_event": "Eventi marini",
    "forest_fire": "Incendi boschivi",
    "avalanches": "Valanghe",
    "thunderstorms": "Temporali",
    "rain": "Pioggia",
    "flooding": "Allagamenti",
    "air_quality": "Qualità dell'aria",
    "dust": "Tempesta di Sabbia/Polveri"
  },
  "messages": {
    "yellow": {
      "event": "Allerta Gialla: {event}",
      "generic": "Allerta Gialla",
      "color": "Giallo"
    },
    "orange": {
      "event": "Allerta Arancione: {event}",
      "generic": "Allerta Arancione",
      "color": "Arancione"
    },
    "red": {
      "event": "Allerta Rossa: {event}",
      "generic": "Allerta Rossa",
      "color": "Rosso"
    }
  }
}
