=== a7rk/MeteoalarmCard/src/localize/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "required": [
        "$schema",
        "common",
        "error",
        "editor",
        "events",
        "messages"
    ],
    "properties": {
         "$schema": {
              "$id": "#/properties/%24schema",
              "type": "string"
         },
        "common": {
            "$id": "#/properties/common",
            "type": "object",
            "required": [
                "name",
                "description",
                "expected",
                "unavailable"
            ],
            "properties": {
                "name": {
                    "$id": "#/properties/common/properties/name",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/common/properties/description",
                    "type": ["string", "null"]
                },
                "expected": {
                    "$id": "#/properties/common/properties/expected",
                    "type": ["string", "null"]
                },
                "unavailable": {
                    "$id": "#/properties/common/properties/unavailable",
                    "type": "object",
                    "required": [
                        "long",
                        "short"
                    ],
                    "properties": {
                        "long": {
                            "$id": "#/properties/common/properties/unavailable/properties/long",
                            "type": ["string", "null"]
                        },
                        "short": {
                            "$id": "#/properties/common/properties/unavailable/properties/short",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "error": {
            "$id": "#/properties/error",
            "type": "object",
            "required": [
                "missing_entity",
                "invalid_integration",
                "invalid_scaling_mode",
                "invalid_display_mode",
                "entity_invalid"
            ],
            "properties": {
                "missing_entity": {
                    "$id": "#/properties/error/properties/missing_entity",
                    "type": ["string", "null"]
                },
                "invalid_integration": {
                    "$id": "#/properties/error/properties/invalid_integration",
                    "type": ["string", "null"]
                },
                "invalid_scaling_mode": {
                    "$id": "#/properties/error/properties/invalid_scaling_mode",
                    "type": ["string", "null"]
                },
                "invalid_display_mode": {
                    "$id": "#/properties/error/properties/invalid_display_mode",
                    "type": ["string", "null"]
                },
                "entity_invalid": {
                    "$id": "#/properties/error/properties/entity_invalid",
                    "type": "object",
                    "required": [
                        "single",
                        "multiple"
                    ],
                    "properties": { 
                        "single": {
                            "$id": "#/properties/error/properties/entity_invalid/properties/single",
                            "type": ["string", "null"]
                        },
                        "multiple": {
                            "$id": "#/properties/error/properties/entity_invalid/properties/multiple",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "editor": {
            "$id": "#/properties/editor",
            "type": "object",
            "required": [
                "entity",
                "entities",
                "integration",
                "required",
                "recommended",
                "override_headline",
                "hide_when_no_warning",
                "hide_caption",
                "disable_swiper",
                "description",
                "error",
                "scaling_mode",
                "scaling_mode_options",
                "display_mode",
                "display_mode_options"
            ],
            "properties": {
                "entity": {
                    "$id": "#/properties/editor/properties/entity",
                    "type": ["string", "null"]
                },
                "entities": {
                    "$id": "#/properties/editor/properties/entities",
                    "type": ["string", "null"]
                },
                "integration": {
                    "$id": "#/properties/editor/properties/integration",
                    "type": ["string", "null"]
                },
                "required": {
                    "$id": "#/properties/editor/properties/required",
                    "type": ["string", "null"]
                },
                "recommended": {
                    "$id": "#/properties/editor/properties/recommended",
                    "type": ["string", "null"]
                },
                "override_headline": {
                  "$id": "#/properties/editor/properties/override_headline",
                  "type": ["string", "null"]
                },
                "hide_when_no_warning": {
                    "$id": "#/properties/editor/properties/hide_when_no_warning",
                    "type": ["string", "null"]
                },
                "hide_caption": {
                    "$id": "#/properties/editor/properties/hide_caption",
                    "type": ["string", "null"]
                },
                "disable_swiper": {
                    "$id": "#/properties/editor/properties/disable_swiper",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/editor/properties/description",
                    "type": "object",
                    "required": [
                        "start",
                        "current_expected",
                        "slots",
                        "separate_events",
                        "warning_watch_statement_advisory",
                        "end"
                    ],
                    "properties": { 
                        "start": {
                            "$id": "#/properties/editor/properties/description/properties/start",
                            "type": ["string", "null"]
                        },
                        "current_expected": {
                            "$id": "#/properties/editor/properties/description/properties/current_expected",
                            "type": ["string", "null"]
                        },
                        "slots": {
                            "$id": "#/properties/editor/properties/description/properties/slots",
                            "type": ["string", "null"]
                        },
                        "separate_events": {
                            "$id": "#/properties/editor/properties/description/properties/separate_events",
                            "type": ["string", "null"]
                        },
                        "warning_watch_statement_advisory": {
                            "$id": "#/properties/editor/properties/description/properties/warning_watch_statement_advisory",
                            "type": ["string", "null"]
                        },
                        "end": {
                            "$id": "#/properties/editor/properties/description/properties/end",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "error": {
                    "$id": "#/properties/editor/properties/error",
                    "type": "object",
                    "required": [
                        "expected_entity",
                        "too_many_entities",
                        "duplicate"
                    ],
                    "properties": { 
                        "expected_entity": {
                            "$id": "#/properties/editor/properties/error/properties/expected_entity",
                            "type": ["string", "null"]
                        },
                        "too_many_entities": {
                            "$id": "#/properties/editor/properties/error/properties/too_many_entities",
                            "type": ["string", "null"]
                        },
                        "duplicate": {
                            "$id": "#/properties/editor/properties/error/properties/duplicate",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "scaling_mode": {
                    "$id": "#/properties/editor/properties/scaling_mode",
                    "type": ["string", "null"]
                },
                "scaling_mode_options": {
                    "$id": "#/properties/editor/properties/scaling_mode_options",
                    "type": "object",
                    "required": [
                        "disabled",
                        "headline",
                        "scale",
                        "headline_and_scale"
                    ],
                    "properties": {
                        "disabled": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/disabled",
                            "type": ["string", "null"]
                        },
                        "headline": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/headline",
                            "type": ["string", "null"]
                        },
                        "scale": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/scale",
                            "type": ["string", "null"]
                        },
                        "headline_and_scale": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/headline_and_scale",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "display_mode": {
                    "$id": "#/properties/editor/properties/display_mode",
                    "type": ["string", "null"]
                },
                "display_mode_options": {
                    "$id": "#/properties/editor/properties/display_mode_options",
                    "type": "object",
                    "required": [
                        "card",
                        "badge"
                    ],
                    "properties": {
                        "card": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/card",
                            "type": ["string", "null"]
                        },
                        "badge": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/badge",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "events": {
            "$id": "#/properties/events",
            "type": "object",
            "required": [
                "no_warnings",
                "nuclear",
                "hurricane",
                "wind",
                "snow_ice",
                "thunderstorms",
                "fog",
                "high_temperature",
                "low_temperature",
                "coastal_event",
                "sea_event",
                "forest_fire",
                "avalanches",
                "earthquake",
                "volcano",
                "rain",
                "flooding",
                "tornado",
                "air_quality",
                "dust",
                "tsunami"
            ],
            "properties": {
                "no_warnings": {
                    "$id": "#/properties/events/properties/no_warnings",
                    "type": ["string", "null"]
                },
                "nuclear": {
                    "$id": "#/properties/events/properties/nuclear",
                    "type": ["string", "null"]
                },
                "hurricane": {
                    "$id": "#/properties/events/properties/hurricane",
                    "type": ["string", "null"]
                },
                "wind": {
                    "$id": "#/properties/events/properties/wind",
                    "type": ["string", "null"]
                },
                "snow_ice": {
                    "$id": "#/properties/events/properties/snow_ice",
                    "type": ["string", "null"]
                },
                "thunderstorms": {
                    "$id": "#/properties/events/properties/thunderstorms",
                    "type": ["string", "null"]
                },
                "fog": {
                    "$id": "#/properties/events/properties/fog",
                    "type": ["string", "null"]
                },
                "high_temperature": {
                    "$id": "#/properties/events/properties/high_temperature",
                    "type": ["string", "null"]
                },
                "low_temperature": {
                    "$id": "#/properties/events/properties/low_temperature",
                    "type": ["string", "null"]
                },
                "coastal_event": {
                    "$id": "#/properties/events/properties/coastal_event",
                    "type": ["string", "null"]
                },
                "sea_event": {
                    "$id": "#/properties/events/properties/sea_event",
                    "type": ["string", "null"]
                },
                "forest_fire": {
                    "$id": "#/properties/events/properties/forest_fire",
                    "type": ["string", "null"]
                },
                "avalanches": {
                    "$id": "#/properties/events/properties/avalanches",
                    "type": ["string", "null"]
                },
                "earthquake": {
                    "$id": "#/properties/events/properties/earthquake",
                    "type": ["string", "null"]
                },
                "volcano": {
                    "$id": "#/properties/events/properties/volcano",
                    "type": ["string", "null"]
                },
                "rain": {
                    "$id": "#/properties/events/properties/rain",
                    "type": ["string", "null"]
                },
                "flooding": {
                    "$id": "#/properties/events/properties/flooding",
                    "type": ["string", "null"]
                },
                "tornado": {
                    "$id": "#/properties/events/properties/tornado",
                    "type": ["string", "null"]
                },
                "air_quality": {
                    "$id": "#/properties/events/properties/air_quality",
                    "type": ["string", "null"]
                },
                "dust": {
                    "$id": "#/properties/events/properties/dust",
                    "type": ["string", "null"]
                },
                "tsunami": {
                    "$id": "#/properties/events/properties/tsunami",
                    "type": ["string", "null"]
                }
            },
            "additionalProperties": false
        },
        "messages": {
            "$id": "#/properties/messages",
            "type": "object",
            "required": [
                "yellow",
                "orange",
                "red"
            ],
            "properties": {
                "yellow": {
                    "$id": "#/properties/messages/properties/yellow",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/yellow/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/yellow/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/yellow/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                },
                "orange": {
                    "$id": "#/properties/messages/properties/orange",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/orange/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/orange/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/orange/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                },
                "red": {
                    "$id": "#/properties/messages/properties/red",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/red/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/red/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/red/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== a7rk/MeteoalarmCard/src/localize/languages/ca.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Targeta Meteoalarm",
    "description": "La targeta Meteoalarm t'avisa sobre els esdeveniments meteorològics actuals.",
    "expected": "Esperat",
    "unavailable": {
      "long": "La integració no està disponible",
      "short": "No disponible"
    }
  },
  "error": {
    "missing_entity": "Cal especificar les entitats!",
    "invalid_integration": "Aquesta integració no és vàlida!",
    "invalid_scaling_mode": "Aquest mode d'escalat no és vàlid!",
    "invalid_display_mode": null,
    "entity_invalid": {
      "single": "La integració seleccionada no coincideix amb l'entitat seleccionada.",
      "multiple": "La integració seleccionada no coincideix amb les entitats seleccionades: {entity}."
    }
  },
  "editor": {
    "entity": "Entitat",
    "entities": null,
    "integration": "Integració",
    "required": "Necessari",
    "recommended": "Recomanat",
    "override_headline": "Sobrescriu el títol proporcionat per la integració",
    "hide_when_no_warning": "Amaga quan no hi ha advertències",
    "hide_caption": "Amaga la descripció",
    "disable_swiper": "Desactiva el desplaçament de les alertes",
    "description": {
      "start": "La integració seleccionada crea múltiples entitats.",
      "current_expected": "La primera amb els esdeveniments actuals i la segona amb els futurs.",
      "slots": "La quantitat exacta d'entitats creades es determina per la seva configuració.",
      "separate_events": "Cada tipus d'esdeveniment té una entitat separada.",
      "warning_watch_statement_advisory": "Hi ha 4 entitats: advertències, vigilàncies, declaracions i avisos.",
      "end": "Hauries d'afegir-les totes per assegurar-te que no et perds cap alerta."
    },
    "error": {
      "expected_entity": "No s'ha proporcionat l'entitat d'advertències esperada. No es mostraran els esdeveniments futurs.",
      "too_many_entities": "S'han proporcionat més entitats de les esperades. S'esperaven {expected_entities_count} entitats, però se n'han proporcionat {selected_entities_count}.",
      "duplicate": "S'han trobat duplicats a la llista d'entitats."
    },
    "scaling_mode": "Mode d'escalat",
    "scaling_mode_options": {
      "disabled": "Desactivat",
      "headline": "Només títol",
      "scale": "Només escala",
      "headline_and_scale": "Títol i escala"
    },
    "display_mode": null,
    "display_mode_options": {
      "card": null,
      "badge": null
    }
  },
  "events": {
    "no_warnings": "Sense advertències",
    "nuclear": "esdeveniment nuclear",
    "tornado": "tornado",
    "hurricane": "huracà",
    "wind": "vent",
    "earthquake": "terratrèmol",
    "volcano": "volcà",
    "snow_ice": "neu/gel",
    "fog": "boira",
    "high_temperature": "temperatura alta",
    "low_temperature": "temperatura baixa",
    "coastal_event": "esdeveniment costaner",
    "tsunami": "tsunami",
    "sea_event": "esdeveniment marítim",
    "forest_fire": "incendi forestal",
    "avalanches": "allaus",
    "thunderstorms": "tempestes",
    "rain": "pluja",
    "flooding": "inundació",
    "air_quality": "qualitat de l'aire",
    "dust": "pols"
  },
  "messages": {
    "yellow": {
      "event": "Alerta groga per {event}",
      "generic": "Alerta groga",
      "color": "Groc"
    },
    "orange": {
      "event": "Alerta taronja per {event}",
      "generic": "Alerta taronja",
      "color": "Taronja"
    },
    "red": {
      "event": "Alerta vermella per {event}",
      "generic": "Alerta vermella",
      "color": "Vermell"
    }
  }
}

=== a7rk/MeteoalarmCard/src/localize/languages/nl.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Kaart",
    "description": "Meteoalarm kaart waarschuwt u voor actuele weersomstandigheden.",
    "expected": "Verwacht",
    "unavailable": {
      "long": "De integratie is niet beschikbaar",
      "short": "Onbeschikbaar"
    }
  },
  "error": {
    "missing_entity": "Het specificeren van de entiteit is vereist!",
    "invalid_integration": "Deze integratie is niet geldig!",
    "invalid_scaling_mode": "Deze schalings modus is niet geldig!",
    "invalid_display_mode": null,
    "entity_invalid": {
      "single": "De geselecteerde integratie komt niet overeen met de geselecteerde entiteit.",
      "multiple": "De geselecteerde integratie komt niet overeen met de geselecteerde entiteiten: {entity}."
    }
  },
  "editor": {
    "entity": "Entiteit",
    "entities": null,
    "integration": "Integratie",
    "required": "Verplicht",
    "recommended": "Aanbevolen",
    "override_headline": "Koptekst overschrijven",
    "hide_when_no_warning": "Verbergen als er geen waarschuwingen zijn",
    "hide_caption": "Verberg onderschrift",
    "disable_swiper": "Schakel waarschuwingen swiper uit",
    "description": {
      "start": "De geselecteerde integratie maakt meerdere entiteiten aan.",
      "current_expected": "De eerste is eerste is een voor een huidige waarschuring en de tweede is voor toekomstige.",
      "slots": "Het precieze aantal is afhankelijk van de configuratie.",
      "separate_events": "Ieder waarschuwingssoort heeft een eigen entiteit.",
      "warning_watch_statement_advisory": "Er zijn 4 entiteittypen: waarschuwingen, berichten, verklaringen en adviezen.",
      "end": "U zult alle typen moeten toevoegen zodat u geen bericht mist."
    },
    "error": {
      "expected_entity": "Er is geen entiteit voor verwachte waarschuwingen opgegeven. Toekomstig evenement wordt niet getoond.",
      "too_many_entities": "Er zijn niet meer entiteiten opgegeven dan verwacht. Verwachtte {expected_entities_count} entiteiten, kreeg {selected_entities_count} entiteiten.",
      "duplicate": "Er zijn duplicaten gevonden in de entiteitenlijst."
    },
    "scaling_mode": "Schalingsmodus",
    "scaling_mode_options": {
      "disabled": "Uitgeschakeld",
      "headline": "Alleen koptekst",
      "scale": "Alleen schalen",
      "headline_and_scale": "Koptekst en schalen"
    },
    "display_mode": null,
    "display_mode_options": {
      "card": null,
      "badge": null
    }
  },
  "events": {
    "no_warnings": "Geen waarschuwingen",
    "nuclear": "nuclear",
    "tornado": "tornado",
    "hurricane": "orkaan",
    "wind": "wind",
    "earthquake": "aardbeving",
    "volcano": "vulkaan",
    "snow_ice": "sneeuw/ijzel/bevriezing",
    "fog": "mist",
    "high_temperature": "zeer hoge temperatuur",
    "low_temperature": "zeer lage temperatuur",
    "coastal_event": "kustbedreiging",
    "tsunami": "tsunami",
    "sea_event": "zeeniveau",
    "forest_fire": "bos- en heidebranden",
    "avalanches": "lawines",
    "thunderstorms": "onweer",
    "rain": "regen",
    "flooding": "overstroming",
    "air_quality": "luchtkwaliteit",
    "dust": "stof"
  },
  "messages": {
    "yellow": {
      "event": "Waarschuwing geel {event}",
      "generic": "Gele waarschuwing",
      "color": "Geel"
    },
    "orange": {
      "event": "Waarschuwing oranje {event}",
      "generic": "Oranje waarschuwing",
      "color": "Oranje"
    },
    "red": {
      "event": "Waarschuwing rood {event}",
      "generic": "Rode waarschuwing",
      "color": "Rood"
    }
  }
}
